### ISSUE TITLE
Date.end_of_week and Date.beginning_of_week returns unexpected dates

### ISSUE THREAD

**Issue by NickNeck** [elixir-cldr/cldr_calendars_coptic#3] opened 2021-09-29 07:12 UTC
Example:
```elixir
iex(1)> date = Date.new!(2020, 07, 05, Cldr.Calendar.Coptic)
~D[2020-07-05 Cldr.Calendar.Coptic]
iex(2)> Date.beginning_of_week(date)
~D[2020-07-07 Cldr.Calendar.Coptic]
iex(3)> date = Date.new!(2020, 07, 14, Cldr.Calendar.Coptic)
~D[2020-07-14 Cldr.Calendar.Coptic]
iex(4)> Date.end_of_week(date)
~D[2020-07-13 Cldr.Calendar.Coptic]
```
See also https://github.com/elixir-lang/elixir/pull/11274

**Comment by kipcole9** [comment] 2021-09-29 11:08
Thanks for the report and apologies for the inconvenience. I believe this is now fixed on the `cldr40` branch.  I will be pushing updates to all the `ex_cldr` libraries in about a week to align with the [CLDR Release 40](https://cldr.unicode.org/index/downloads/cldr-40) data.  Are you ok to wait for that? If not, let me know and I'll see if I can package this up for earlier availability.

The documentation for `Date.day_of_week/1` is intentionally ambiguous as to whether the day of the week is intended to be an ordinal day or a cardinal day. I have always thought of it as a cardinal day, I believe José considers is more an ordinal day - and thats why `Calendar.day_of_week/4` callback returns a tuple `{day_of_week, first_day_of_week_cardinal, last_day_of_week_cardinal}`. 

Would you expect `day_of_week` in this case to be - the ordinal day of the week or the cardinal day of the week?

**Comment by NickNeck** [comment] 2021-10-01 05:34
Hello @kipcole9 

Sorry for the late feedback. I was on a short vacation. It is okay for me to wait for the next update. 

I would expect that `day_of_week` is the cardinal day of the week.

Thank you, for your great work.

**Comment by kipcole9** [comment] 2021-10-03 14:59
Thanks for the support and encouragement.

I've published [release 1.0.0-rc.0](https://hex.pm/packages/ex_cldr_calendars_coptic/1.0.0-rc.0) that I believe includes fixes for `day_of_week/3` that was the cause of the issue you raised.  If you have a chance to try it out and let me know if it returns what you expect that would be great.  I won't be pushing a formal release for another couple of weeks.  The changelog entry is:

### Bug fixes

* Fix `day_of_week/3`. Thanks to @NickNeck for the report. Closes #3.

### Enhancements

* Now based upon the template calendar in `Cldr.Calendar.Behaviour`

**Comment by NickNeck** [comment] 2021-10-03 18:24
I have try it and everything looks fine for me 👍

**Comment by kipcole9** [comment] 2021-10-03 21:20
Thanks much for trying it out and glad its working as you expect.

**Closed as completed by kipcole9** 2021-10-03 21:20 UTC
